### PR TITLE
lecture 03 (draft #1)

### PR DESCRIPTION
**Pull request by gaelforget**
This PR initially contained an outline of what I have in mind for lecture 03. Additional commits tomorrow and Thu will add text, links, images, etc for each bullet in the lists. Merging the PR can wait but I can also submit more PRs later if you decide to merge.

Please feel free to comment, suggest changes, etc

### CODE REVIEW

**Comment by hdrake** [comment]
Great, I'll take a look after my lecture today!

**Comment by gaelforget** [comment]
If that makes sense, I propose:

- I do one more commit to the PR after cleaning up the `Lecture03_project_infrastructure.md` by 2pm30
- @hdrake then merges this PR and email attendees about tomorrow's session (pointing them to preliminary `Lecture03_project_infrastructure.md`)

Would this work?

**Comment by hdrake** [comment]
That sounds like a good plan @gaelforget, although I might not get around to it until 4:30 or so.

**Comment by gaelforget** [comment]
By the way, the new `binder/apt.txt` installs the `nano` text editor and `gfortran` compiler which will likely be useful for later sessions too.

**Comment by gaelforget** [comment]
@hdrake 

> That sounds like a good plan @gaelforget, although I might not get around to it until 4:30 or so.

Cool. I just did the announced `2pm30 commit`. Feel free to merge and email when good for you. 

Ideally, if you get a chance, please rebuild / trigger binder to see that it works before emailing folks.

On my end I will keep at it and might push more commits to this PR branch as long as it remains open -- or start a new PR branch once you have merged this one

ok?

**Comment by gaelforget** [comment]
Like the pics I added?

**Comment by hdrake** [comment]
Looks good to me. I like the pictures! Really looking forward to this tomorrow – I think I'll learn a lot! Sending out the email now.

**Pull request merged**
